server.port: 9090
spring.datasource.url: jdbc:postgresql://localhost/LAB1
spring.datasource.username: postgres
spring.datasource.password: kusuma01
spring.datasource.driver.class: org.postgresql.Driver
